### ISSUE TITLE
right side 'D' in D-ENMU is cut

### ISSUE THREAD

**Issue by wkitty42** [gilbertohasnofb/c172p-detailed-liveries#2]
i just noticed this and don't recall having seen it before but the 'D' on the right side of the D-ENMU livery is cut off...

![D-EMNU right side](https://www.dropbox.com/s/zcmjrpyov0ecj8o/fgfs-screen-091.png?dl=1)

**Comment by gilbertohasnofb** [comment]
Yeah, my bad, it happened when we made the stabilizers slimmer and I had to make some tricks to the tail texture. I will fix it straight away.

**Comment by gilbertohasnofb** [comment]
By the way, it's better to report this kind of stuff in the main repository, this repo here serves only to save the files. I am copying your report there.

**Comment by gilbertohasnofb** [comment]
See: https://github.com/Juanvvc/c172p-detailed/issues/570

**Comment by wkitty42** [comment]
ok... i wasn't sure if to report here or there... as long as it is seen and fixed in both places we're good :smile_cat:

**Comment by gilbertohasnofb** [comment]
No worrie. I just think that the other repo is better because I think I am the only one pushing stuff to this repository here and I am not sure anyone else reads these. Also, this way we keep all reports together in one single place :smile:

**Comment by wkitty42** [comment]
:+1:
